export enum LoadOffers {
  PENDING = 'LOAD_OFFERS/PENDING',
  RESOLVE = 'LOAD_OFFERS/RESOLVE',
  REJECT = 'LOAD_OFFERS/REJECT',
}

export enum UpdateOffer {
  PENDING = 'UPDATE_OFFER/PENDING',
  RESOLVE = 'UPDATE_OFFER/RESOLVE',
  REJECT = 'UPDATE_OFFER/REJECT',
}
